/**
 * This file is auto-generated. Do not edit directly.
 * Generated by scripts/generate_static_types.sh
 */
#pragma once
#ifndef __FELIX_HASHMAP_FLOAT_LONG_H__
#define __FELIX_HASHMAP_FLOAT_LONG_H__

#include "__internals/__type_gen_macro.h"
HASHMAP_DEFINE_TYPE(float, float, long, long)

#endif // __FELIX_HASHMAP_FLOAT_LONG_H__
