/**
 * This file is auto-generated. Do not edit directly.
 * Generated by scripts/generate_static_types.sh
 */
#pragma once
#ifndef __FELIX_HASHMAP_CHAR_CHAR_H__
#define __FELIX_HASHMAP_CHAR_CHAR_H__

#include "helpers/_helper.h"
HASHMAP_DEFINE_TYPE(char, char, char, char)

#endif // __FELIX_HASHMAP_CHAR_CHAR_H__
