/**
 * This file is auto-generated. Do not edit directly.
 * Generated by scripts/generate_static_types.sh
 */
#pragma once
#ifndef __FELIX_HASHMAP_FLOAT_INT_H__
#define __FELIX_HASHMAP_FLOAT_INT_H__

#include "helpers/_helpers.h"
HASHMAP_DEFINE_TYPE(float, float, int, int)

#endif // __FELIX_HASHMAP_FLOAT_INT_H__
