/**
 * This file is auto-generated. Do not edit directly.
 * Generated by scripts/generate_static_types.sh
 */
#pragma once
#ifndef __FELIX_HASHMAP_STRING_CHAR_H__
#define __FELIX_HASHMAP_STRING_CHAR_H__

#include "helpers/_helper_string.h"
HASHMAP_DEFINE_STRING_TYPE(char, char)

#endif // __FELIX_HASHMAP_STRING_CHAR_H__
