#!/usr/bin/env bash

CURRENT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
mkdir -p "${CURRENT_DIR}/../include/types/"
echo "Generating static hashmap types..."

define() {
    echo -e "✅ [${1},\t${2}\t]"
    cat > "${CURRENT_DIR}/../include/types/${1}_${2}.h" <<EOF
/**
 * This file is auto-generated. Do not edit directly.
 * Generated by scripts/generate_static_types.sh
 */
#pragma once
#ifndef __FELIX_HASHMAP_${1^^}_${2^^}_H__
#define __FELIX_HASHMAP_${1^^}_${2^^}_H__

#include "__internals/__type_gen_macro.h"
HASHMAP_DEFINE_TYPE(${1}, ${1}, ${2}, ${2})

#endif // __FELIX_HASHMAP_${1^^}_${2^^}_H__
EOF
}

define_string() {
    echo -e "✅ [string,\t${1}\t]"
    cat > "${CURRENT_DIR}/../include/types/string_${1}.h" <<EOF
/**
 * This file is auto-generated. Do not edit directly.
 * Generated by scripts/generate_static_types.sh
 */
#pragma once
#ifndef __FELIX_HASHMAP_STRING_${1^^}_H__
#define __FELIX_HASHMAP_STRING_${1^^}_H__

#include "__internals/__string_gen_macro.h"
HASHMAP_DEFINE_STRING_TYPE(${1}, ${1})

#endif // __FELIX_HASHMAP_STRING_${1^^}_H__
EOF
}

GENERATE_TYPE=(int float double char)

for KEY_TYPE in "${GENERATE_TYPE[@]}"; do
    for VALUE_TYPE in "${GENERATE_TYPE[@]}"; do
        define "${KEY_TYPE}" "${VALUE_TYPE}"
    done
done

# for string
for VALUE_TYPE in "${GENERATE_TYPE[@]}"; do
    define_string "${VALUE_TYPE}"
done
