#!/usr/bin/env bash

CURRENT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

define() {
    echo "Generating hashmap helpers for key: ${1} value: ${2}"
    cat > "${CURRENT_DIR}/../include/helpers/${1}_${2}.h" <<EOF
/**
 * This file is auto-generated. Do not edit directly.
 * Generated by scripts/generate_static_types.sh
 */
#pragma once
#ifndef __FELIX_HASHMAP_${1^^}_${2^^}_H__
#define __FELIX_HASHMAP_${1^^}_${2^^}_H__

#include "helpers/_helper.h"
HASHMAP_DEFINE_TYPE(${1}, ${1}, ${2}, ${2})

#endif // __FELIX_HASHMAP_${1^^}_${2^^}_H__
EOF
}

define_string() {
    echo "Generating hashmap helpers for key: string value: ${1}"
    cat > "${CURRENT_DIR}/../include/helpers/string_${1}.h" <<EOF
/**
 * This file is auto-generated. Do not edit directly.
 * Generated by scripts/generate_static_types.sh
 */
#pragma once
#ifndef __FELIX_HASHMAP_STRING_${1^^}_H__
#define __FELIX_HASHMAP_STRING_${1^^}_H__

#include "helpers/_helper_string.h"
HASHMAP_DEFINE_STRING_TYPE(${1}, ${1})

#endif // __FELIX_HASHMAP_STRING_${1^^}_H__
EOF
}

GENERATE_TYPE=(int float double char)

for KEY_TYPE in "${GENERATE_TYPE[@]}"; do
    for VALUE_TYPE in "${GENERATE_TYPE[@]}"; do
        define "${KEY_TYPE}" "${VALUE_TYPE}"
    done
done

# for string
for VALUE_TYPE in "${GENERATE_TYPE[@]}"; do
    define_string "${VALUE_TYPE}"
done
