/**
 * This file is auto-generated. Do not edit directly.
 * Generated by scripts/generate_types.sh
 */
#pragma once
#ifndef __FELIX_HASHMAP_DOUBLE_DOUBLE_H__
#define __FELIX_HASHMAP_DOUBLE_DOUBLE_H__

#include "__internals/__type_gen_macro.h"
HASHMAP_DEFINE_TYPE(double, double, double, double)

#endif // __FELIX_HASHMAP_DOUBLE_DOUBLE_H__
