/**
 * This file is auto-generated. Do not edit directly.
 * Generated by scripts/generate_types.sh
 */
#pragma once
#ifndef __FELIX_HASHMAP_STRING_CHAR_H__
#define __FELIX_HASHMAP_STRING_CHAR_H__

#include "__internals/__string_gen_macro.h"
HASHMAP_DEFINE_STRING_TYPE(char, char)

#endif // __FELIX_HASHMAP_STRING_CHAR_H__
